uuid = "e780b8ef-aae3-4abf-ad05-b9d33427762d"

[deps]
BasicBSpline = "4c5d9882-2acf-4ea4-9e48-968fd4518195"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Debugger = "31a5f54b-26ea-5ae9-a837-f05ce5417438"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
Eyeball = "ce36242b-ad83-4f84-8519-47cd8aeefd60"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Gaston = "4b11ee91-296f-5714-9832-002c20994614"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
MasterThesis = "27635c0a-2b2b-45f9-9c89-acc1396f8bb7"
Measures = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
preBurner = "386a581c-36dc-455e-918c-a2c2dae4c8f2"
